### ISSUE TITLE
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).

### ISSUE THREAD

**Issue by Hiiragi0107** [schelotto/Wasserstein-AutoEncoders#11]
This happens when you run wae_gan.py. What is the solution?

##################
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).

**Comment by sheepc** [comment]
you can rewrite wae_gan.py line157 to one = torch.tensor(1.),it works for me.

**Comment by Hiiragi0107** [comment]
Sorry for the delay in replying
Thanks for telling me!
