### ISSUE TITLE
mmd_loss.backward() gets an error

### ISSUE THREAD

**Issue by ahmed-fau** [schelotto/Wasserstein-AutoEncoders#2]
Hi,

I am encountering the following error when backwarding through the mmd_loss function

'Traceback (most recent call last):
  File "wae.py", line 570, in <module>
    mmd_loss.mean().backward(retain_graph=True)
  File "/home/amust/toolchain/lib/python3.5/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/amust/toolchain/lib/python3.5/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.'

Any help to fix this ?

Best Regards

**Comment by zehuichen123** [comment]
It seems that I met the same error: 
```
Traceback (most recent call last):
  File "wae_gan.py", line 192, in <module>
    torch.log(d_fake).mean().backward(mone)
  File "/home/czw/.conda/envs/lovesnowbest/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/czw/.conda/envs/lovesnowbest/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]
```

**Comment by ahmed-fau** [comment]
I think that I have got the solution:

the backward function of the reconstruction loss (recon_loss.backward(one)) should be called with argument 'retain_graph=True'. Otherwise, the computation graph for the encoder would be freed and the mmd_loss backward function will raise an error.

so:

reconstruction_loss.backward(retain_graph=True)
mmd_loss.mean().backward()

**Comment by zehuichen123** [comment]
emm, maybe we met the same problem but they were caused by different reasons. My error log was slightly different from yours, maybe that's why your solution doesn't work for me :(

**Comment by schelotto** [comment]
I've fixed that bug. MMD loss and recon loss are now summed before back prop, instead of back prop separately.
