### ISSUE TITLE
Possible issue in IMQ implementation?

### ISSUE THREAD

**Issue by tolstikhin** [schelotto/Wasserstein-AutoEncoders#3]
Hey! First of all, thanks for the effort --- It is good to see WAE implemented on the PyTorch!

I was recently pointed to this implementation with some questions regarding the IMQ kernel.
I noticed that [these lines](https://github.com/schelotto/Wasserstein_Autoencoders/blob/3b4a0449c1ab4fbfcc4d620dc17c7f7f52ff3806/wae_mmd.py#L119-L125) of your code seem to forget squaring the coordinates before summing them during the computations of norms. Could you verify this? It may be the case that my PyTorch skills are not so good and I'm missing something.

Best wishes,
Ilya

**Comment by schelotto** [comment]
Hi Ilya,

Thanks for noticing my implementation of WAE in PyTorch.

You're correct, and I modified the code by squaring them before summing over coordinates for X^2 and y^2 terms, and the cross product term remains unchanged.

Best,
Canran
